version: "3.7"

services:
  redis:
    image: redis:3
    container_name: example_redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    container_name: example_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - "mysql_data:/var/lib/mysql"