spring:
  application:
    name: "lock-example"
  datasource:
    lock:
      url: ${LOCK_DATASOURCE:jdbc:mysql://localhost:3306/test}
      password: ${LOCK_PASSWORD:1q2w3e4r}
      username: ${LOCK_USERNAME:root}
      driverClassName: com.mysql.cj.jdbc.Driver
    default:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true}
      password: ${DATASOURCE_PASSWORD:1q2w3e4r}
      username: ${DATASOURCE_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
logging:
  level:
    com:
      zaxxer:
        hikari: info