spring:
  application:
    name: "lock-example"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true}
    password: ${DATASOURCE_PASSWORD:1q2w3e4r}
    username: ${DATASOURCE_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

logging:
  level:
    com:
      zaxxer:
        hikari: error